### ISSUE TITLE
Problem installing libv8 on mac

### ISSUE THREAD

**Issue by seekshiva** [cowboyd/libv8#135]
I get the following error while trying to install libv8 in OS X 10.10 Yosemite. Can someone help me with it?

```
Vs-MacBook-Air:courses shiva$ sudo gem install libv8
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
    ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.6
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Unable to find a compiler officially supported by v8.
It is recommended to use GCC v4.4 or higher
Using compiler: g++
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Unable to find a compiler officially supported by v8.
It is recommended to use GCC v4.4 or higher
../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
                 ^
1 error generated.
make[1]: *** [/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
make: *** [x64.release] Error 2
/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
    from /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:35:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:35:in `verify_installation!'
    from /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:26:in `install!'
    from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
    build/gyp/gyp --generator-output="out" build/all.gyp \
                  -Ibuild/standalone.gypi --depth=. \
                  -Dv8_target_arch=x64 \
                  -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
  CXX(target) /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/libv8-3.16.14.3/ext/libv8/gem_make.out
Vs-MacBook-Air:courses shiva$ 

```

**Comment by marceloboeira** [comment]
gem install libv8 -v '3.16.14.3' -- --with-system-v8

**Comment by dsimm** [comment]
This worked for me out on macOS Sierra 
gem install libv8 -v '3.16.14.11' -- --with-system-v8

**Comment by ignisf** [comment]
@dsimm I just released a binary for macOS sierra, please try resetting your bundler configuration and updating the gem. --with-system-v8 should not be needed.

**Comment by unquabain** [comment]
Regarding `--with-system-v8`, the libv8 docs have this to say:

> This is a great way to ensure that the builds of all gems that depend on libv8 fail.
https://github.com/cowboyd/libv8#bring-your-own-v8

And that's exactly what happened for me.
