### ISSUE TITLE
libv8 3.16.14.7 fails to build pn ppc64le

### ISSUE THREAD

**Issue by grepwood** [cowboyd/libv8#170]
```
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.9
Using compiler: /usr/bin/g++
In file included from ../src/allocation.h:31:0,
                 from ../src/allocation.cc:28:
../src/globals.h:90:2: error: #error Host architecture was not detected as supported by v8
 #error Host architecture was not detected as supported by v8
  ^
../src/globals.h:116:2: error: #error Target architecture x64 is only supported on x64 host
 #error Target architecture x64 is only supported on x64 host
  ^
make[1]: *** [/var/lib/gems/2.1.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o] Error 1
make: *** [x64.release] Error 2
/var/lib/gems/2.1.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/var/lib/gems/2.1.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from /var/lib/gems/2.1.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:35:in `each'
        from /var/lib/gems/2.1.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:35:in `verify_installation!'
        from /var/lib/gems/2.1.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=x64 \
              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3
make[1]: Entering directory '/var/lib/gems/2.1.0/gems/libv8-3.16.14.3/vendor/v8/out'
  CXX(target) /var/lib/gems/2.1.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
tools/gyp/preparser_lib.target.x64.mk:112: recipe for target '/var/lib/gems/2.1.0/gems/libv8-3.16.14.3/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o' failed
make[1]: Leaving directory '/var/lib/gems/2.1.0/gems/libv8-3.16.14.3/vendor/v8/out'
Makefile:195: recipe for target 'x64.release' failed

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/libv8-3.16.14.3 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/powerpc64le-linux/2.1.0/libv8-3.16.14.3/gem_make.out
```

**Comment by ignisf** [comment]
Unfortunately v8 3.16 has no ppc support as can be seen here: https://github.com/v8/v8/blob/7ce3fe106a37826dc23189a78dcb9000a1b3fa06/src/globals.h#L65

It's infeasible to go after support for this arch without migrating to a fresher version of v8, which has been underway for a while now but progress is extremely slow.

**Comment by ignisf** [comment]
You can however take the https://github.com/cowboyd/libv8/tree/trunk branch for a spin and see what you can do to get it to compile.
