### ISSUE TITLE
Publish 3.16.4.9?

### ISSUE THREAD

**Issue by bronson** [cowboyd/libv8#175]
This page shows that 3.16.14.9 is out: https://github.com/cowboyd/libv8/releases

But this page shows that it hasn't been published to rubygems: https://rubygems.org/gems/libv8

Is it just a matter of time?

I ask because right now building 3.16.14.8 is failing on my machine...  Hoping a binary release will make this irrelevant.

**Comment by bronson** [comment]
Here's the error, fwiw:

```
~/project (master)↑⚡$ bundle update libv8
Fetching gem metadata from https://rubygems.org/............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
...
Using less 2.6.0
Using less-rails 2.7.0
Using less-rails-bootstrap 3.3.4.0

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/bronson/.rubies/ruby-2.0.0-p481/bin/ruby -r ./siteconf20150630-24868-v56wmx.rb extconf.rb 
creating Makefile
Compiling v8 for x64
Using python 2.7.6
Using compiler: /usr/bin/c++ (clang version 6.1.0)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o has no symbols
In file included from ../src/accessors.cc:28:
In file included from ../src/v8.h:60:
In file included from ../src/objects-inl.h:38:
In file included from ../src/elements.h:33:
In file included from ../src/heap.h:35:
In file included from ../src/incremental-marking.h:33:
In file included from ../src/mark-compact.h:32:
../src/spaces.h:896:26: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  bool exists() { return this != NULL && code_range_ != NULL; }
                         ^~~~    ~~~~
../src/spaces.h:898:9: error: 'this' pointer cannot be null in well-defined C++ code; comparison may be assumed to always evaluate to false [-Werror,-Wtautological-undefined-compare]
    if (this == NULL || code_range_ == NULL) return false;
        ^~~~    ~~~~
2 errors generated.
make[1]: *** [/Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
make: *** [x64.release] Error 2
/Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/ext/libv8/location.rb:35:in `each'
	from /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/diy-fp.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/dtoa.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fast-dtoa.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/fixed-dtoa.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/preparser-api.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/scanner.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/strtod.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/token.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/unicode.o
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser_lib/src/utils.o
  LIBTOOL-STATIC /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/libpreparser_lib.a
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/preparser/preparser/preparser-process.o
  LINK(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/preparser
  CXX(target) /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o

extconf failed, exit code 1

Gem files will remain installed in /Users/bronson/.gem/ruby/2.0.0/gems/libv8-3.16.14.8 for inspection.
Results logged to /Users/bronson/.gem/ruby/2.0.0/extensions/x86_64-darwin-14/2.0.0-static/libv8-3.16.14.8/gem_make.out
An error occurred while installing libv8 (3.16.14.8), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.16.14.8'` succeeds before bundling.
```

**Comment by envygeeks** [comment]
It was put up and yanked for some reason.

**Comment by tagliala** [comment]
the reason probably is: #172

**Comment by born4new** [comment]
Yup, we have that issue aswell, will stay to a lower version for the time being.

**Comment by cowboyd** [comment]
`3.16.14.11` is now out.
