### ISSUE TITLE
72633b8 fails to install on OSX  10.11.4

### ISSUE THREAD

**Issue by kyledecot** [cowboyd/libv8#209]
I just attemped to install libv8 from master (72633b8) and received the following error:

 ```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8
/Users/kyledecot/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20160426-88483-wrgbbf.rb extconf.rb
creating Makefile
ln: build/gyp: No such file or directory
/Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/patcher.rb:52:in `block (2 levels) in patch!': failed to apply patch (RuntimeError)
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/patcher.rb:50:in `each'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/patcher.rb:50:in `block in patch!'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/patcher.rb:46:in `open'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/patcher.rb:46:in `patch!'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/builder.rb:57:in `block in build_libv8!'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/builder.rb:52:in `chdir'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/builder.rb:52:in `build_libv8!'
	from /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'```

extconf failed, exit code 1

Gem files will remain installed in /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/libv8-72633b893938 for inspection.
Results logged to /Users/kyledecot/.rvm/gems/ruby-2.3.1@trellis/bundler/gems/extensions/x86_64-darwin-15/2.3.0/libv8-72633b893938/gem_make.out

**Comment by ignisf** [comment]
Make sure you list it in your Gemfile with `submodules: true` as documented here: https://github.com/cowboyd/libv8#using-a-git-version

**Comment by ignisf** [comment]
I assume you've specified `submodules: true` as documented here: https://github.com/cowboyd/libv8#using-a-git-version?

**Comment by ignisf** [comment]
Closing this for now. New version released, so you shouldn't have to use git.
