### ISSUE TITLE
non-standart arch and compiler

### ISSUE THREAD

**Issue by nfedoseev** [cowboyd/libv8#222]
HI.

We have machine with non-standart arch and compiler. So, we unable to complile library

```
Compiling v8 for x64
Using python 2.7.9
Using compiler: g++ (GCC version 4.4.0)
Beginning compilation. This will take some time.
/usr/lib64/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:31:in
`make_flags': undefined method `include?' for nil:NilClass (NoMethodError)
        from
/usr/lib64/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:70:in
`block in build_libv8!'
        from
/usr/lib64/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:54:in
`chdir'
        from
/usr/lib64/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/builder.rb:54:in
`build_libv8!'
        from
/usr/lib64/ruby/gems/2.2.0/gems/libv8-3.16.14.15/ext/libv8/location.rb:24:in
`install!'
        from extconf.rb:7:in `<main>'
```

**Comment by nfedoseev** [comment]
After delete function for flags again have problems(

```
 bundle exec rake compile
ruby ext/libv8/extconf.rb
creating Makefile
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "managed": False,
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
'
Running: gclient sync --with_branch_heads
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_                                                                                                                                                             auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1'                                                                                                                                                              returned non-zero exit status 1 in /root/libv8/vendor
Traceback (most recent call last):
  File "/root/libv8/vendor/depot_tools/fetch.py", line 353, in <module>
    sys.exit(main())
  File "/root/libv8/vendor/depot_tools/fetch.py", line 348, in main
    return run(options, spec, root)
  File "/root/libv8/vendor/depot_tools/fetch.py", line 342, in run
    return checkout.init()
  File "/root/libv8/vendor/depot_tools/fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "/root/libv8/vendor/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/root/libv8/vendor/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads                                                                                                                                                             ')' returned non-zero exit status 2
/root/libv8/ext/libv8/builder.rb:89:in `block in setup_build_deps!': unable to f                                                                                                                                                             etch v8 source (RuntimeError)
        from /root/libv8/ext/libv8/builder.rb:87:in `chdir'
        from /root/libv8/ext/libv8/builder.rb:87:in `setup_build_deps!'
        from /root/libv8/ext/libv8/builder.rb:43:in `build_libv8!'
        from /root/libv8/ext/libv8/location.rb:24:in `install!'
        from ext/libv8/extconf.rb:7:in `<main>'
rake aborted!
Command failed with status (1): [ruby ext/libv8/extconf.rb...]
/root/libv8/Rakefile:22:in `block in <top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => compile
(See full trace by running task with --trace)
```

**Comment by ignisf** [comment]
Hello,

Could you please include the version output of your compiler? With GCC and Clang this is achieved by invoking the compiler with a `-v` flag.

Keep in mind that v8 is VERY picky about compiler support. We're doing quite a lot of patching just to make sure it compiles on newer versions of the compilers supported by upstream v8. I fear that it might not be at all possible to compile with something else.

**Comment by nfedoseev** [comment]
lcc:1.20.14:Dec-29-2015:***-linux
gcc (GCC) 4.4.0 compatible

**Comment by ignisf** [comment]
Please test

https://github.com/cowboyd/libv8/commits/lcc-support-3.16

https://github.com/cowboyd/libv8/tree/lcc-support

**Comment by nfedoseev** [comment]
lcc-support

```
bundle exec rake compile
ruby ext/libv8/extconf.rb
creating Makefile
/root/libv8/ext/libv8/builder.rb:106:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
        from /root/libv8/ext/libv8/builder.rb:104:in `chdir'
        from /root/libv8/ext/libv8/builder.rb:104:in `setup_build_deps!'
        from /root/libv8/ext/libv8/builder.rb:60:in `build_libv8!'
        from /root/libv8/ext/libv8/location.rb:24:in `install!'
        from ext/libv8/extconf.rb:7:in `<main>'
rake aborted!
```

**Comment by nfedoseev** [comment]
lcc-support-3.16

```
bundle exec rake compile
ruby ext/libv8/extconf.rb
creating Makefile
HEAD is now at 2f0efde... Version 3.16.14
Can't locate SVN/Core.pm in @INC (@INC contains: /usr/lib/perl5/site_perl/5.16.3/***-linux /usr/lib/perl5/site_perl/5.16.3 /usr/lib/perl5/5.16.3/***-linux /usr/lib/perl5/5.16.3 /usr/lib/perl5 .) at /usr/lib/perl5/site_perl/5.16.3/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.16.3/Git/SVN/Utils.pm line 6.
Compilation failed in require at /usr/lib/perl5/site_perl/5.16.3/Git/SVN.pm line 26.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.16.3/Git/SVN.pm line 33.
Compilation failed in require at /usr/libexec/git-core/git-svn line 25.
BEGIN failed--compilation aborted at /usr/libexec/git-core/git-svn line 25.
/root/libv8/ext/libv8/checkout.rb:48:in `check_git_svn!': git-svn not installed! (RuntimeError)
Please install git-svn.
        from /root/libv8/ext/libv8/checkout.rb:24:in `checkout!'
        from /root/libv8/ext/libv8/builder.rb:52:in `build_libv8!'
        from /root/libv8/ext/libv8/location.rb:24:in `install!'
        from ext/libv8/extconf.rb:7:in `<main>'
rake aborted!
Command failed with status (1): [ruby ext/libv8/extconf.rb...]
/root/libv8/Rakefile:25:in `block in <top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => compile
(See full trace by running task with --trace)
```

**Comment by ignisf** [comment]
Well, now you have two unrelated to the compiler issues.

The issue with the 3.16 branch is that you have not satisfied the `git-svn` dependency it has.

The issue with the branch based on master is that the v8 source fetch operation fails for some reason.
You can debug what's going on there by adding the `vendor/depot_tools` directory to your path and running `fetch v8`.

As a matter of fact are you sure that the repo has been [cloned recursively](https://github.com/cowboyd/libv8/tree/lcc-support#what-if-i-cant-install-from-source)?

**Comment by ignisf** [comment]
Also, unless your compiler has C++11 support, it's pointless trying to get the master branch to compile. There's a slim possibility for the 3.16 branch though.

**Comment by ignisf** [comment]
Also, is the compiler open source or are you working with your own fork?

**Comment by nfedoseev** [comment]
v5.1.281.67.0-3-g9b20a18

```
~/libv8/vendor/depot_tools # ./fetch v8
Running: gclient root
Traceback (most recent call last):
  File "./fetch.py", line 353, in <module>
    sys.exit(main())
  File "./fetch.py", line 348, in main
    return run(options, spec, root)
  File "./fetch.py", line 334, in run
    if not options.force and checkout.exists():
  File "./fetch.py", line 80, in exists
    gclient_root = self.run_gclient('root').strip()
  File "./fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "./fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by ignisf** [comment]
You need to have them in your `PATH` variable. See https://www.chromium.org/developers/how-tos/install-depot-tools

**Comment by nfedoseev** [comment]
Compiler created for a closed system based on Debian 7 and custom CPU arch and able to work with Intel x86.

btw very thx for your great support!

**Comment by ignisf** [comment]
Ping me when you've tried 3.16 after installing svn, or whatever is necessary for git-svn support.

**Comment by nfedoseev** [comment]
Ok, I'm now compling git-svn

**Comment by nfedoseev** [comment]
:-1: 

```
# git svn
Can't locate SVN/Core.pm in @INC (@INC contains: /usr/lib/perl5/site_perl/5.16.3/e2k-linux /usr/lib/perl5/site_perl/5.16.3 /usr/lib/perl5/5.16.3/e2k-linux /usr/lib/perl5/5.16.3 /usr/lib/perl5 .) at /usr/lib/perl5/site_perl/5.16.3/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.16.3/Git/SVN/Utils.pm line 6.
Compilation failed in require at /usr/lib/perl5/site_perl/5.16.3/Git/SVN.pm line 26.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.16.3/Git/SVN.pm line 33.
Compilation failed in require at /usr/libexec/git-core/git-svn line 25.
BEGIN failed--compilation aborted at /usr/libexec/git-core/git-svn line 25.
```

```
# find / -type f -name 'Core.pm'
/usr/libexec/perf-core/scripts/perl/Perf-Trace-Util/lib/Perf/Trace/Core.pm
/usr/lib64/perl5/site_perl/5.16.3/e2k-linux/File/FcntlLock/Core.pm
```

```
# ls -la /usr/lib
lrwxrwxrwx 1 root root 5 ��� 31  2015 /usr/lib -> lib64
```

**Comment by ignisf** [comment]
OK, so. I consider the compiler detection issue itself to be resolved by the code changes in the branches. You are welcome to fork and use them, however I don't think it's a good idea merge them in this project.

You are welcome to open up another issue for the source fetching issues you are hitting how.
