### ISSUE TITLE
Error: Command '/home/vagrant/libv8/python v8/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 1 in /home/vagrant/libv8/vendor

### ISSUE THREAD

**Issue by ignisf** [cowboyd/libv8#233]
OS FreeBSD 10&11

```
env MAKEFLAGS+=-j4 bundle exec rake binary'
ruby ext/libv8/extconf.rb
creating Makefile
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Error: Command '/home/vagrant/libv8/python v8/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 1 in /home/vagrant/libv8/vendor
Traceback (most recent call last):
  File "/home/vagrant/libv8/vendor/depot_tools/fetch.py", line 300, in <module>
    sys.exit(main())
  File "/home/vagrant/libv8/vendor/depot_tools/fetch.py", line 295, in main
    return run(options, spec, root)
  File "/home/vagrant/libv8/vendor/depot_tools/fetch.py", line 289, in run
    return checkout.init()
  File "/home/vagrant/libv8/vendor/depot_tools/fetch.py", line 132, in init
    self.run_gclient(*sync_cmd)
  File "/home/vagrant/libv8/vendor/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/vagrant/libv8/vendor/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2
/home/vagrant/libv8/ext/libv8/builder.rb:112:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /home/vagrant/libv8/ext/libv8/builder.rb:110:in `chdir'
	from /home/vagrant/libv8/ext/libv8/builder.rb:110:in `setup_build_deps!'
	from /home/vagrant/libv8/ext/libv8/builder.rb:66:in `build_libv8!'
	from /home/vagrant/libv8/ext/libv8/location.rb:24:in `install!'
	from ext/libv8/extconf.rb:7:in `<main>'
rake aborted!
Command failed with status (1): [ruby ext/libv8/extconf.rb...]
/home/vagrant/libv8/Rakefile:22:in `block in <top (required)>'
/home/vagrant/libv8/vendor/bundle/ruby/2.2/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => binary => compile
(See full trace by running task with --trace)
```

**Comment by avkarenow** [comment]
Hello,

any ideas how to compile gem libv8 on FreeBSD 10/11? I have the same issue - tested on FreeBSD 10, from source, gem install libv8 etc. without success.

**Comment by ignisf** [comment]
yes.

`env GYPFLAGS+="make_clang_dir=" gem install libv8`

**Comment by ignisf** [comment]
Must find two minutes of free time to commit a fix........

**Comment by avkarenow** [comment]
I tried that command on clean environment: FreeBSD 10.3 + rvm, but still the same problem appeared:
```$ env GYPFLAGS="make_clang_dir=" gem install libv8
Fetching: libv8-5.3.332.38.5.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    current directory: /usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/ext/libv8
/home/test0/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20170324-43464-1a8u9r0.rb extconf.rb
creating Makefile
Error: Command '/usr/local/bin/python v8/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 1 in /usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "managed": False,
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 353, in <module>
    sys.exit(main())
  File "/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 348, in main
    return run(options, spec, root)
  File "/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 342, in run
    return checkout.init()
  File "/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/vendor/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2
/usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:109:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:107:in `chdir'
	from /usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:107:in `setup_build_deps!'
	from /usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/ext/libv8/builder.rb:63:in `build_libv8!'
	from /usr/home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/test0/.rvm/gems/ruby-2.3.1/gems/libv8-5.3.332.38.5 for inspection.
Results logged to /home/test0/.rvm/gems/ruby-2.3.1/extensions/x86_64-freebsd-10/2.3.0/libv8-5.3.332.38.5/gem_make.out```

**Comment by ignisf** [comment]
Sorry I wasted your time, it's `GYP_DEFINES`

**Comment by avkarenow** [comment]
It works, thank you for help.
