### ISSUE TITLE
Gem build fails at Arch Linux

### ISSUE THREAD

**Issue by anatol** [cowboyd/libv8#241]
I am trying to build the gem at Arch Linux. This distributive uses the latest build tool that might cause the problem. Anyway here is the build log:

```
Building native extensions.  This could take a while...
ERROR:  Error installing libv8-5.7.492.65.1.gem:
	ERROR: Failed to build gem native extension.

    current directory: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8
/usr/bin/ruby -r ./siteconf20170719-645-7znv4w.rb extconf.rb
creating Makefile
which: no python in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was ee15703e6c... [parser] Prohibit async functions and generators in invalid contexts
HEAD is now at 518c07c067... Version 5.7.492.65

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/gypfiles/landmines.py' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s v8/buildtools/win/clang-format.exe.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
The current platform doesn't match "darwin", skipping.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
0> Downloading v8/buildtools/linux64/clang-format...
Success!
Downloading 1 files took 4.616325 second(s)

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/tools/gcmole/download_gcmole_tools.py' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
Skipping gcmole download as gcmole is not set in gyp flags.

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/tools/jsfunfuzz/download_jsfunfuzz.py' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
Skipping jsfunfuzz download as jsfunfuzz is not set in gyp flags.

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-luci -d v8/tools/luci-go/win64' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-luci -d v8/tools/luci-go/mac64' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
The current platform doesn't match "darwin", skipping.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
0> Downloading v8/tools/luci-go/linux64/isolate...
Success!
Downloading 1 files took 5.909161 second(s)

________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-gn -s v8/buildtools/win/gn.exe.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-gn -s v8/buildtools/mac/gn.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
The current platform doesn't match "darwin", skipping.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
0> Downloading v8/buildtools/linux64/gn...
Success!
Downloading 1 files took 4.141307 second(s)

________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-fuzzer -s v8/test/fuzzer/wasm.tar.gz.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
0> Downloading v8/test/fuzzer/wasm.tar.gz...
0> Extracting 646 entries from v8/test/fuzzer/wasm.tar.gz to v8/test/fuzzer/wasm
Success!
Downloading 1 files took 4.282901 second(s)

________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-asmjs-fuzzer -s v8/test/fuzzer/wasm_asmjs.tar.gz.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
0> Downloading v8/test/fuzzer/wasm_asmjs.tar.gz...
0> Extracting 172 entries from v8/test/fuzzer/wasm_asmjs.tar.gz to v8/test/fuzzer/wasm_asmjs
Success!
Downloading 1 files took 4.133698 second(s)

________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
0> File v8/src/inspector/build/closure-compiler.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.009714 second(s)

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
Installing Debian Wheezy amd64 root image: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/build/linux/debian_wheezy_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/08b780f0ee9b1c60724ad8c8024bd84cc8a6d928/debian_wheezy_amd64_sysroot.tgz
Installing Debian Wheezy i386 root image: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/build/linux/debian_wheezy_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/08b780f0ee9b1c60724ad8c8024bd84cc8a6d928/debian_wheezy_i386_sysroot.tgz
Installing Debian Precise amd64 root image: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/build/linux/ubuntu_precise_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/08b780f0ee9b1c60724ad8c8024bd84cc8a6d928/ubuntu_precise_amd64_sysroot.tgz
Hook '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 38.25 secs

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/third_party/instrumented_libraries/scripts/download_binaries.py' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/build/vs_toolchain.py update' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/third_party/binutils/download.py' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/gypfiles/download_gold_plugin.py' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
Skipping gold plugin download for non-cfi build.

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/tools/clang/scripts/update.py --if-needed' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
Skipping Clang update (make_clang_dir= was set in GYP_DEFINES).

________ running '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/python v8/gypfiles/gyp_v8 --running-as-hook' in '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor'
GYP is now disabled by default in runhooks.

If you really want to run this, either run 
`python gypfiles/gyp_v8` explicitly by hand 
or set the environment variable GYP_CHROMIUM_NO_ACTION=0.

WARNING: 'v8/buildtools/third_party/libunwind/trunk' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/test/wasm-js' is no longer part of this client.  It is recommended that you manually remove it.

Applying /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/patches/0001-Build-a-standalone-static-library.patch
Applying /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/patches/0002-Don-t-compile-unnecessary-stuff.patch
Applying /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/patches/0003-Use-the-fPIC-flag-for-the-static-library.patch
Applying /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/patches/0004-Do-not-embed-debug-symbols-in-macOS-libraries.patch
Compiling v8 for x64
Using python 2.7.13
Using compiler: g++ (GCC version 7.1.1)
Beginning compilation. This will take some time.
Building v8 with env CXX=g\+\+ /usr/bin/make x64.release i18nsupport=off werror=no GYP_DEFINES="v8_use_external_startup_data=0 use_sysroot=0 linux_use_bundled_binutils=0 linux_use_bundled_gold=0 make_clang_dir="" clang_dir="" clang=0"
PYTHONPATH="/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/tools/generate_shim_headers:/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/gypfiles::/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/tools/gyp/pylib:" \
GYP_GENERATORS=make \
tools/gyp/gyp --generator-output="out" gypfiles/all.gyp \
              -Igypfiles/standalone.gypi --depth=. \
              -Dv8_target_arch=x64 \
               -Dtarget_arch=x64 \
               \
              -S.x64.release  -Dv8_enable_backtrace=1 -Dwerror='' -Dv8_enable_i18n_support=0 -Darm_fpu=default -Darm_float_abi=default
make[1]: Entering directory '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out'
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/bits.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/cpu.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/division-by-constant.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/debug/stack_trace.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/file-utils.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/functional.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/ieee754.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/logging.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/once.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/platform/time.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/platform/condition-variable.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/platform/mutex.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/platform/semaphore.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/sys-info.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/utils/random-number-generator.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/debug/stack_trace_posix.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/platform/platform-linux.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_libbase/src/base/platform/platform-posix.o
  AR(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/src/libv8_libbase.a
  COPY /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/libv8_libbase.a
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/mkpeephole/src/interpreter/bytecode-operands.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/mkpeephole/src/interpreter/bytecodes.o
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/mkpeephole/src/interpreter/mkpeephole.o
  LINK(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/mkpeephole
  ACTION src_v8_gyp_v8_base_target_run_mkpeephole /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_base/geni/bytecode-peephole-table.cc
  CXX(target) /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o
In file included from .././src/heap/heap.h:21:0,
                 from .././src/contexts.h:8,
                 from .././src/api.h:9,
                 from ../src/accessors.cc:7:
.././src/objects.h: In member function ‘uint32_t v8::internal::HashTable<Derived, Shape, Key>::Hash(Key)’:
.././src/objects.h:3505:46: warning: invalid use of incomplete type ‘class v8::internal::Heap’
       return Shape::SeededHash(key, GetHeap()->HashSeed());
                                              ^~
In file included from .././src/accessors.h:8:0,
                 from ../src/accessors.cc:5:
.././include/v8.h:146:7: note: forward declaration of ‘class v8::internal::Heap’
 class Heap;
       ^~~~
In file included from .././src/heap/heap.h:21:0,
                 from .././src/contexts.h:8,
                 from .././src/api.h:9,
                 from ../src/accessors.cc:7:
.././src/objects.h: In member function ‘uint32_t v8::internal::HashTable<Derived, Shape, Key>::HashForObject(Key, v8::internal::Object*)’:
.././src/objects.h:3513:55: warning: invalid use of incomplete type ‘class v8::internal::Heap’
       return Shape::SeededHashForObject(key, GetHeap()->HashSeed(), object);
                                                       ^~
In file included from .././src/accessors.h:8:0,
                 from ../src/accessors.cc:5:
.././include/v8.h:146:7: note: forward declaration of ‘class v8::internal::Heap’
 class Heap;
       ^~~~
In file included from .././src/heap/objects-visiting.h:13:0,
                 from .././src/heap/object-stats.h:12,
                 from .././src/heap/heap-inl.h:15,
                 from .././src/objects-inl.h:24,
                 from .././src/arguments.h:9,
                 from .././src/debug/debug.h:9,
                 from .././src/x64/assembler-x64-inl.h:11,
                 from .././src/assembler-inl.h:13,
                 from .././src/macro-assembler.h:8,
                 from .././src/deoptimizer.h:10,
                 from ../src/accessors.cc:9:
.././src/objects-body-descriptors.h: In static member function ‘static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*, int)’:
.././src/objects-body-descriptors.h:102:20: error: no matching function for call to ‘v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*&)’
     IterateBody(obj);
                    ^
.././src/objects-body-descriptors.h:84:22: note: candidate: template<int start_offset, int end_offset, int size> template<class ObjectVisitor> static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*, ObjectVisitor*)
   static inline void IterateBody(HeapObject* obj, ObjectVisitor* v) {
                      ^~~~~~~~~~~
.././src/objects-body-descriptors.h:84:22: note:   template argument deduction/substitution failed:
.././src/objects-body-descriptors.h:102:20: note:   candidate expects 2 arguments, 1 provided
     IterateBody(obj);
                    ^
.././src/objects-body-descriptors.h:89:22: note: candidate: template<int start_offset, int end_offset, int size> template<class ObjectVisitor> static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*, int, ObjectVisitor*)
   static inline void IterateBody(HeapObject* obj, int object_size,
                      ^~~~~~~~~~~
.././src/objects-body-descriptors.h:89:22: note:   template argument deduction/substitution failed:
.././src/objects-body-descriptors.h:102:20: note:   candidate expects 3 arguments, 1 provided
     IterateBody(obj);
                    ^
.././src/objects-body-descriptors.h:95:22: note: candidate: template<int start_offset, int end_offset, int size> template<class StaticVisitor> static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*)
   static inline void IterateBody(HeapObject* obj) {
                      ^~~~~~~~~~~
.././src/objects-body-descriptors.h:95:22: note:   template argument deduction/substitution failed:
.././src/objects-body-descriptors.h:102:20: note:   couldn't deduce template parameter ‘StaticVisitor’
     IterateBody(obj);
                    ^
.././src/objects-body-descriptors.h:101:22: note: candidate: template<int start_offset, int end_offset, int size> template<class StaticVisitor> static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*, int)
   static inline void IterateBody(HeapObject* obj, int object_size) {
                      ^~~~~~~~~~~
.././src/objects-body-descriptors.h:101:22: note:   template argument deduction/substitution failed:
.././src/objects-body-descriptors.h:102:20: note:   candidate expects 2 arguments, 1 provided
     IterateBody(obj);
                    ^
make[1]: *** [src/v8_base.target.x64.release.mk:648: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/v8_base/src/accessors.o] Error 1
make[1]: Leaving directory '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out'
make: *** [Makefile:310: x64.release] Error 2
/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/location.rb:41:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/location.rb:40:in `each'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/location.rb:40:in `verify_installation!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-5.7.492.65.1 for inspection.
Results logged to /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/libv8-5.7.492.65.1/gem_make.out
```

**Comment by ignisf** [comment]
Hi. Will take a closer look

**Comment by ignisf** [comment]
OK. The patch for this will be in the next release. In the meantime you could use the `master` version. I hope it won't be too long before I have 5.9 out.

**Comment by ignisf** [comment]
Patch in question: https://github.com/cowboyd/libv8/blob/e442d538814f10138ab51c2a0b1c56b88135fa28/patches/0005-Fix-GCC-7-build-errors.patch
