### ISSUE TITLE
v8 patches failed to apply

### ISSUE THREAD

**Issue by anatol** [cowboyd/libv8#246]
I am building `libv8` using rubygem and it fails with the error below.

Note that I am using rubygems that already includes `vendor/v8` directory content without `.git` dir. Thus `git checkout #{source_version}` in `setup_build_deps!` function fails and I had to remove it. Could it be that gem includes incorrect version of v8 (e.g. `master` branch)?

```
Building native extensions.  This could take a while...
ERROR:  Error installing libv8-6.0.286.54.1.gem:
	ERROR: Failed to build gem native extension.

    current directory: /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8
/usr/bin/ruby -r ./siteconf20170828-669-d76qi1.rb extconf.rb
creating Makefile
which: no python in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Bootstrapping cipd client for linux-amd64 from https://chrome-infra-packages.appspot.com/client?platform=linux-amd64&version=git_revision:cf5b0de14e94b06274d15e84b19449f580576e80...
[0:01:00] Still working on:
[0:01:00]   v8
[0:01:10] Still working on:
[0:01:10]   v8
[0:01:20] Still working on:
[0:01:20]   v8
[0:01:30] Still working on:
[0:01:30]   v8
[0:01:40] Still working on:
[0:01:40]   v8
[0:01:50] Still working on:
[0:01:50]   v8
[0:02:00] Still working on:
[0:02:00]   v8
[0:02:10] Still working on:
[0:02:10]   v8
[0:02:19] Still working on:
[0:02:19]   v8


Warnings:
Conflicting directory /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/vendor/v8 moved to /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/vendor/_bad_scm/v8rxFro0.
error: pathspec 'Makefile' did not match any file(s) known to git.
Applying /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/patches/0001-Build-a-standalone-static-library.patch
Applying /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/patches/0002-Don-t-compile-unnecessary-stuff.patch
/build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/patcher.rb:15:in `block (2 levels) in patch!': failed to apply patch /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/patches/0002-Don-t-compile-unnecessary-stuff.patch (RuntimeError)
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/patcher.rb:12:in `each'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/patcher.rb:12:in `block in patch!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/patcher.rb:8:in `open'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/patcher.rb:8:in `patch!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:74:in `block in build_libv8!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:72:in `chdir'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:72:in `build_libv8!'
	from /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/gems/libv8-6.0.286.54.1 for inspection.
Results logged to /build/ruby-libv8/pkg/ruby-libv8/usr/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/libv8-6.0.286.54.1/gem_make.out
```

**Comment by ignisf** [comment]
Hello,

Thank you for the report!

Could you please share the output of running `gem env` on your system?

**Comment by anatol** [comment]
```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/anatol/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/anatol/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /home/anatol/.gem/ruby/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/anatol/.cargo/bin
     - /usr/local/buildtools/java/jdk/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /home/anatol/bin
```

I am downloading gem source file and installing it as a local file:

```
$ sha1sum libv8-6.0.286.54.1.gem 
a9fa244fb43451e503773829a07dd2605a838dcf  libv8-6.0.286.54.1.gem

$ gem install --user libv8 libv8-6.0.286.54.1.gem
WARNING:  You don't have /home/anatol/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    current directory: /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8
/usr/bin/ruby2.3 -r ./siteconf20170828-36999-144u8g1.rb extconf.rb
creating Makefile
fatal: Not a git repository (or any parent up to mount point /usr/local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!': unable to checkout source for v8 6.0.286.54 (RuntimeError)
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:115:in `chdir'
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:115:in `setup_build_deps!'
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:71:in `build_libv8!'
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1 for inspection.
Results logged to /home/anatol/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/libv8-6.0.286.54.1/gem_make.out
Building native extensions.  This could take a while...
ERROR:  Error installing libv8-6.0.286.54.1.gem:
	ERROR: Failed to build gem native extension.

    current directory: /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8
/usr/bin/ruby2.3 -r ./siteconf20170828-36999-mzzy34.rb extconf.rb
creating Makefile
fatal: Not a git repository (or any parent up to mount point /usr/local)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!': unable to checkout source for v8 6.0.286.54 (RuntimeError)
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:115:in `chdir'
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:115:in `setup_build_deps!'
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/builder.rb:71:in `build_libv8!'
	from /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/anatol/.gem/ruby/2.3.0/gems/libv8-6.0.286.54.1 for inspection.
Results logged to /home/anatol/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/libv8-6.0.286.54.1/gem_make.out
```

**Comment by ignisf** [comment]
Ah, I see, thank you! Will fix ASAP

**Comment by anatol** [comment]
Hi Petko, any update on it? Is there a quick fix that I can apply locally util a new fixed version of `libv8` released.

**Comment by anatol** [comment]
Hello @ignisf any update on this issue?

**Comment by anatol** [comment]
@ignisf it is an important regression that blocks many of us. Any chance to see it fixed?

**Comment by ignisf** [comment]
working on it

**Comment by ignisf** [comment]
Will do a bit more testing and release a new 6.0 binary. 6.2 needs more work.
