### ISSUE TITLE
Fails to build on OSX High Sierra 

### ISSUE THREAD

**Issue by theycallmeswift** [cowboyd/libv8#256]
I'm having trouble installing libv8 as part of therubyracer on OSX High Sierra (v10.13.2).  Error log is copied below.  Let me know what other info I can share that would be helpful!

**Input**:

```
$ gem install libv8 -v '3.16.14.19'
```

**Output**:

```
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    current directory: /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8
/Users/theycallmeswift/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20180111-6586-g262oz.rb extconf.rb
creating Makefile
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/disable-building-tests.patch
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/disable-werror-on-osx.patch
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/disable-xcode-debugging.patch
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/do-not-imply-vfp3-and-armv7.patch
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/do-not-use-MAP_NORESERVE-on-freebsd.patch
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/do-not-use-vfp2.patch
Applying /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/patches/fPIC-for-static.patch
Compiling v8 for x64
Using python 2.7.10
Using compiler: c++ (GCC version 6.3.1)
Beginning compilation. This will take some time.
Building v8 with env CXX=c++ LINK=c++  /usr/bin/make x64.release ARFLAGS.target=crs werror=no
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
c++: error: unrecognized command line option '-Wnewline-eof'
make[1]: *** [/Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o] Error 1
make: *** [x64.release] Error 2
/Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `each'
	from /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/libv8-3.16.14.19 for inspection.
Results logged to /Users/theycallmeswift/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0-static/libv8-3.16.14.19/gem_make.out
```

**Comment by ignisf** [comment]
Hi,

Thank you for the report. In the meantime I've pushed darwin-17 binaries to Rubygems. Try installing again.

**Comment by theycallmeswift** [comment]
@ignisf thanks for pushing those.  I was able to reinstall successfully.  Should we update the "Do I get a binary?" section of the README to reflect that darwin-17 is now supported?

**Comment by ignisf** [comment]
3.16 binaries will get repackaged for future macOS versions.
