### ISSUE TITLE
libv8-3.16.14.15: Segmentation fault

### ISSUE THREAD

**Issue by blshkv** [cowboyd/libv8#264]
I'm unable to compile an old version of libv8 with a gcc 7.3.0.
I'm not sure if you are willing to support this request, but that version is required for therubyracer.

The relevant shapshot is below, I can provide a full build log if required

```
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(__StaticAssertTypedef__, __LINE__)
     ^~~~~~~~~~~~~~~~
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^~~~~~~~~~~~
../src/api.h:129:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT(sizeof(T) == sizeof(v8::internal::Address));
   ^~~~~~~~~~~~~
  LINK(target) /data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/mksnapshot
  ACTION tools_gyp_v8_gyp_v8_snapshot_target_run_mksnapshot /data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/v8_snapshot/geni/snapshot.cc
/bin/sh: line 1: 28400 Segmentation fault      "/data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/mksnapshot" --log-snapshot-positions --logfile "/data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/v8_snapshot/geni/snapshot.log" "/data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/v8_snapshot/geni/snapshot.cc"
gmake[1]: *** [tools/gyp/v8_snapshot.target.x64.mk:13: /data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/v8_snapshot/geni/snapshot.cc] Error 139
gmake[1]: Leaving directory '/data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out'
gmake: *** [Makefile:195: x64.release] Error 2
/data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_snapshot.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
        from /data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/ext/libv8/location.rb:35:in `each'
        from /data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/ext/libv8/location.rb:35:in `verify_installation!'
        from /data/notmpfs/portage/dev-ruby/libv8-3.16.14.15/work/ruby23/libv8-3.16.14.15/ext/libv8/location.rb:26:in `install!'
        from extconf.rb:7:in `<main>'

```

**Comment by blshkv** [comment]
FYI, it might be something to with bad code and ```--strict-aliasing``` workaround, but I did not find a solution.

There are random similar reports such as:
https://freeswitch.org/jira/browse/FS-10977
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826955

and random patches, but none of them worked here

**Comment by blshkv** [comment]
the workaround is to use "snapshot=off":

```
--- ext/libv8/builder.rb.orig   2018-07-22 08:46:32.555026647 +0800
+++ ext/libv8/builder.rb        2018-07-22 08:47:19.588029204 +0800
@@ -22,6 +22,9 @@
     end
 
     def make_flags(*flags)
+
+      flags << "snapshot=off"
+
       # FreeBSD uses gcc 4.2 by default which leads to
       # compilation failures due to warnings about aliasing.
       # http://svnweb.freebsd.org/ports/head/lang/v8/Makefile?view=markup
--- ext/libv8/paths.rb.orig     2018-07-22 09:16:24.477124058 +0800
+++ ext/libv8/paths.rb  2018-07-22 09:24:22.528150045 +0800
@@ -11,7 +11,7 @@
     end
 
     def object_paths
-      [libv8_object(:base), libv8_object(:snapshot)].map do |path|
+      [libv8_object(:base), libv8_object(:nosnapshot)].map do |path|
         Shellwords.escape path
       end
     end

--- spec/location_spec.rb.orig  2018-07-22 08:46:32.558026647 +0800
+++ spec/location_spec.rb       2018-07-22 09:01:37.475075840 +0800
@@ -64,7 +64,7 @@
     end
 
     it "prepends the locations of any libv8 objects on the the ldflags" do
-      @context.ldflags.should eql "/foo\\ bar/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a /foo\\ bar/v8/out/x64.release/obj.target/tools/gyp/libv8_snapshot.a -lobjc -lpthread"
+      @context.ldflags.should eql "/foo\\ bar/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a /foo\\ bar/v8/out/x64.release/obj.target/tools/gyp/libv8_nosnapshot.a -lobjc -lpthread"
     end
   end
 end
```

**Comment by ignisf** [comment]
Hello,

Have you considered migrating to `mini_racer` instead?

**Comment by blshkv** [comment]
this dep **was** required by beef and they have migrated to nodejs in https://github.com/beefproject/beef/pull/1591.
I'll suggest it.

**Comment by ignisf** [comment]
Well, I already suggested to them to move to mini_racer, they decided not to, then when beef stopped working on newer versions of kali, I suggested they move to node and made a PR that got merged. See the author of the issue you linked.

**Comment by ignisf** [comment]
Will close this for now -- trying to maintain this old version of v8 is not practical :/

**Comment by blshkv** [comment]
Agreed, thank you for you quick responses.
