### ISSUE TITLE
Publish 3.16.14.19-x86_64-darwin-18 build to rubygems

### ISSUE THREAD

**Issue by lloeki** [cowboyd/libv8#266]
As it turns out, [cowboyd/therubyracer depends on ~> 3.16.14.15](https://github.com/cowboyd/therubyracer/blob/56da5e54751feca3a1ae056001c8cc469fdd641e/therubyracer.gemspec#L20), therefore it would be extremely helpful of someone to have `libv8-3.16.14.19-x86_64-darwin-18.gem` on rubygems.org, and since I see there's both [libv8-3.16.14.19-x86_64-darwin-17.gem](https://rubygems.org/gems/libv8/versions/3.16.14.19-x86_64-darwin-17) (which isn't even on the [releases page](https://github.com/cowboyd/libv8/releases/tag/v3.16.14.19)) and `libv8-6.7.288.46.1-x86_64-darwin-18.gem` I ventured that maybe Mojave support isn't out of the picture for the 3.16.14 line?

**Comment by ignisf** [comment]
Hey,

I will repackage it, thanks for the reminder

**Comment by lloeki** [comment]
Awesome, thanks! (I'm pulling my hair right now to rebuild it locally and it keeps on failing for me 😭)

**Comment by ignisf** [comment]
Could you test if https://github.com/cowboyd/libv8/releases/download/v3.16.14.19/libv8-3.16.14.19-x86_64-darwin-18.gem works for you before I push it to rubygems?

**Comment by lloeki** [comment]
A simple test with therubyracer 0.12.3 is working!

```
$ bundle show | grep -e libv8 -e therubyracer
  * libv8 (3.16.14.19)
  * therubyracer (0.12.3)
$ bundle exec pry
[1] pry(main)> require 'v8'
=> true
[2] pry(main)> cxt = V8::Context.new
=> #<V8::Context:0x00007fcfb69a8bb0
 @access=#<V8::Access:0x00007fcfb69a80c0>,
 @conversion=#<V8::Conversion:0x00007fcfb69a8598>,
 @native=#<V8::C::Context:0x00007fcfb69a22d8>,
 @timeout=nil>
[3] pry(main)> cxt.eval('7 * 6') #=> 42
=> 42
```

**Comment by ignisf** [comment]
awesome! I just pushed it.

**Comment by raguay** [comment]
I'm getting this:

```
❯ sudo gem install therubyracer
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181013-46428-1su3eeu.rb extconf.rb
creating Makefile
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/disable-building-tests.patch
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/disable-werror-on-osx.patch
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/disable-xcode-debugging.patch
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/do-not-imply-vfp3-and-armv7.patch
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/do-not-use-MAP_NORESERVE-on-freebsd.patch
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/do-not-use-vfp2.patch
Applying /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/patches/fPIC-for-static.patch
Compiling v8 for x64
Using python 2.7.15
Using compiler: c++ (Apple LLVM version 10.0.0)
Unable to find a compiler officially supported by v8.
It is recommended to use GCC v4.4 or higher
Beginning compilation. This will take some time.
Building v8 with env CXX=c++ LINK=c++  /usr/bin/make x64.release ARFLAGS.target=crs werror=no
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_enable_backtrace=1 -Dv8_can_use_vfp2_instructions=true -Darm_fpu=vfpv2 -Dv8_can_use_vfp3_instructions=true -Darm_fpu=vfpv3 -Dwerror=''
  CXX(target) /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/allocation.cc:33:
../src/utils.h:33:10: fatal error: 'climits' file not found
#include <climits>
         ^~~~~~~~~
1 warning and 1 error generated.
make[1]: *** [/Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o] Error 1
make: *** [x64.release] Error 2
/Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:35:in `verify_installation!'
	from /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/libv8-3.16.14.19 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/libv8-3.16.14.19/gem_make.out
```

I need it for handlebars gem.

**Comment by shir** [comment]
How came to this with same error `fatal error: 'climits' file not found`. Here is a workaround which helped me:

```sh
$ gem install libv8 -v '3.16.14.15' -- --with-system-v8 
```

**Comment by anandraj007** [comment]
@raguay  could you please tell me how did you solve the problem .I am getting the same error in mac os newest version.

**Comment by raguay** [comment]
@anandraj007 I never did myself. I left using ruby and am now doing everything in nodejs. But, you should try what @shir says to do above. It might help.

**Comment by anandraj007** [comment]
Thanks, I'll check it out.
